# Managed by GitHub labeler workflow. Edit this file and push to sync.
- name: wontfix
  color: ffffff
  description: This will not be worked on
- name: Duplicate
  color: cfd3d7
  description: This issue or pull request already exists

# Type
- name: "Type: Bug"
  color: 0052cc
  description: Unexpected behavior requiring fix
- name: "Type: Feature"
  color: 0052cc
  description: New user-facing functionality or improvement
- name: "Type: Tech Task"
  color: 0052cc
  description: Non-user-facing code, infra, or refactoring work
- name: "Type: Research"
  color: 0052cc
  description: Spike, POC, or feasibility analysis needed
- name: "Type: Question"
  color: 0052cc
  description: Needs clarification or discussion
- name: "Type: Documentation"
  color: 0052cc
  description: Content updates, guides, or API references
- name: "Type: Epic"
  color: 0052cc
  description: Large initiative grouping multiple tickets

# Status
- name: "Status: Ready for Dev"
  color: 0e8a16
  description: Fully specified, dependencies resolved, approved - good to start coding
- name: "Status: Needs Spec"
  color: 0e8a16
  description: Missing requirements, designs, or technical validation
- name: "Status: Needs QA"
  color: 0e8a16
  description: Dev complete - needs testing, verification, defect logging
- name: "Status: In Review"
  color: 0e8a16
  description: PR submitted - needs feedback/approval
- name: "Status: Blocked"
  color: 0e8a16
  description: External dependency - requires action to unblock

# Severity
- name: "Severity: Critical"
  color: 610230
  description: System down, legal risk, revenue loss - drop everything
- name: "Severity: High"
  color: 610230
  description: Core broken, no workaround - fix within 24h
- name: "Severity: Medium"
  color: 610230
  description: Partial issue, has workaround - next sprint
- name: "Severity: Low"
  color: 610230
  description: Cosmetic, docs, edge case - backlog

# Priority
- name: P0
  color: fbca04
  description: Site down, security breach
- name: P1
  color: fbca04
  description: Major feature blocked
- name: P2
  color: fbca04
  description: Key user journey impact
- name: P3
  color: fbca04
  description: General improvements
- name: P4
  color: fbca04
  description: Low urgency / nice to have

# Impact
- name: "Impact: UX"
  color: 006b75
  description: Improves user experience (e.g., page load time)
- name: "Impact: Risk"
  color: 006b75
  description: Reduces compliance/security risks (e.g., GDPR compliance)
- name: "Impact: Revenue"
  color: 006b75
  description: Directly affects sales/conversion (e.g., checkout flow)
- name: "Impact: Growth"
  color: 006b75
  description: User acquisition/retention (e.g., referral program)
- name: "Impact: Cost"
  color: 006b75
  description: Lowers operational costs (e.g., server optimization)

# Complexity (estimation proxy)
- name: "Complexity: 1"
  color: 5a338b
  description: Lowest complexity
- name: "Complexity: 2"
  color: 5a338b
  description: Very low complexity
- name: "Complexity: 3"
  color: 5a338b
  description: Low complexity
- name: "Complexity: 4"
  color: 5a338b
  description: Low-medium complexity
- name: "Complexity: 5"
  color: 5a338b
  description: Medium complexity
- name: "Complexity: 6"
  color: 5a338b
  description: Medium-high complexity
- name: "Complexity: 7"
  color: 5a338b
  description: High complexity
- name: "Complexity: 8"
  color: 5a338b
  description: Very high complexity
- name: "Complexity: 9"
  color: 5a338b
  description: Extreme complexity
- name: "Complexity: 10"
  color: 5a338b
  description: Highest complexity

# Agent routing
- name: "Agent: Developer"
  color: 0939cd
  description: To be solved by a Developer
- name: "Agent: Background"
  color: 0939cd
  description: To be solved by Cursor Background Agent