name: "🐛 Bug report"
description: "Report a bug"
title: "[Bug] <Title>"
labels: ["Type: Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill the details below.
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear and concise description of the bug.
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Provide steps, code snippets, commands, URLs, or screenshots.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS, Node, browser, app version, etc.
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste relevant logs or stack traces.
      render: shell
  - type: checkboxes
    id: regression
    attributes:
      label: Is this a regression?
      options:
        - label: Yes, it worked before
        - label: No, new issue
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria (optional)
      description: Clear, testable conditions to consider this done
      placeholder: |
        - [ ] Condition 1
        - [ ] Condition 2
      render: markdown
    validations:
      required: false
  - type: textarea
    id: stakeholders
    attributes:
      label: Stakeholders (optional)
      placeholder: PM, QA, designers, external partners
  - type: textarea
    id: dependencies_pm
    attributes:
      label: Dependencies (optional)
      placeholder: Related features, blocked by, links
  - type: textarea
    id: risk_assumptions
    attributes:
      label: Risks & Assumptions (optional)
      placeholder: Known risks, constraints, assumptions
  - type: textarea
    id: pm_notes
    attributes:
      label: PM Notes for Devs (optional)
      placeholder: Additional context, goals, scope boundaries, resources, links