name: "🎨 Design"
description: "Design task (UX/UI, visual, interaction)"
title: "[Design] <brief description>"
labels: ["Type: Design"]
body:
  - type: textarea
    id: brief
    attributes:
      label: Brief
      placeholder: What are we designing and why?
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements & constraints
  - type: textarea
    id: deliverables
    attributes:
      label: Deliverables
      placeholder: Wireframes, mocks, prototypes, specs
  - type: textarea
    id: references
    attributes:
      label: References
      placeholder: Inspiration, prior art, links
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria (optional)
      description: Clear, testable conditions to consider this done
      placeholder: |
        - [ ] Approved design deliverables attached
        - [ ] Accessibility reviewed
        - [ ] Edge cases documented
      render: markdown
    validations:
      required: false
  - type: textarea
    id: stakeholders
    attributes:
      label: Stakeholders (optional)
      placeholder: PM, Designers, QA, Engineering
  - type: textarea
    id: pm_notes
    attributes:
      label: PM Notes for Devs (optional)
      placeholder: Additional context, goals, scope boundaries, resources, links