name: "📝 Documentation"
description: "Docs improvements or additions"
title: "[Docs] <Title>"
labels: ["Type: Documentation"]
body:
  - type: textarea
    id: scope
    attributes:
      label: Scope
      placeholder: What needs to be documented?
    validations:
      required: true
  - type: textarea
    id: audience
    attributes:
      label: Audience
      placeholder: Who is this documentation for?
  - type: textarea
    id: references
    attributes:
      label: References
      placeholder: Links to related docs, issues, PRs