name: "✨ Feature request"
description: "Propose a new feature"
title: "[Feature] <Title>"
labels: ["Type: Feature"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the problem this feature solves and the desired outcome.
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      placeholder: What user problem are we solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      placeholder: Describe your proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: scope
    attributes:
      label: Out of scope
  - type: checkboxes
    id: impacts
    attributes:
      label: Areas impacted
      options:
        - label: API
        - label: UI/UX
        - label: Performance
        - label: Security
        - label: Docs
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria (optional)
      description: Clear, testable conditions to consider this done
      placeholder: |
        - [ ] Condition 1
        - [ ] Condition 2
      render: markdown
    validations:
      required: false
  - type: textarea
    id: stakeholders
    attributes:
      label: Stakeholders (optional)
      placeholder: PM, QA, designers, external partners
  - type: textarea
    id: dependencies_pm
    attributes:
      label: Dependencies (optional)
      placeholder: Related features, blocked by, links
  - type: textarea
    id: risk_assumptions
    attributes:
      label: Risks & Assumptions (optional)
      placeholder: Known risks, constraints, assumptions
  - type: textarea
    id: pm_notes
    attributes:
      label: PM Notes for Devs (optional)
      placeholder: Additional context, goals, scope boundaries, resources, links