name: "Question"
description: "Ask a question or request support"
title: "[❓ Type: Question] <Title>"
labels: ["Type: Question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: Describe your question or support need
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      placeholder: Context, steps, screenshots, or links
  - type: input
    id: environment
    attributes:
      label: Environment (optional)
      placeholder: OS, Node, browser, app version, etc.